### ISSUE TITLE
Pass assets as string array

### ISSUE THREAD

**Issue by RobinHSanner** [mitmadness/AssetBundleCompiler#2]
Doing this:
await bundle('/abs/path/to/fbx', '/abs/path/to/texture', /* ... */)
works great when you hard code it but if you want to pass in the parameters from say a JSON array it doesn't work.

**Comment by RobinHSanner** [comment]
For instance having the following object to use as input to the bundle

{
    "target": "iOS",
    "files": [ "/Models/model.fbx", "/Models/texture01.jpg" ],
    "output": "/Models/resources.assetbundle"
}

**Comment by RobinHSanner** [comment]
Never mind  using bundle(...inputFiles) solved it

**Comment by toverux** [comment]
Yes, I'm happy that you solved this before I could help :)

For future readers that aren't used to ES 6+ syntaxes yet, I can recommend this:

 - [Rest parameters `function(...args)` on the MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters)
 - [Spread syntax `call(...myArguments);` on the MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)
