### ISSUE TITLE
Where to place AssetBundleCompiler class

### ISSUE THREAD

**Issue by zippopalermo** [mitmadness/AssetBundleCompiler#7]
I keep running into the following error:

Aborting batchmode due to failure:
executeMethod class 'AssetBundleCompiler' could not be found.
Argument was -executeMethod AssetBundleCompiler.Convert

Can anybody tell me where to place this class? Is it in the Editor directory of the Unity instance?

Please enlighten me :)

**Comment by toverux** [comment]
Hi,

Actually, this should be automatic. The library copies the script to the right project folder: https://github.com/mitmadness/AssetBundleCompiler/blob/master/src/unity_project.ts#L41
The library should throw an error if that step fails though. Please check that the file is copied to `${ProjectDirectory}/Assets/Editor/AssetBundleCompiler.cs` in the temporary project the library creates.
Maybe something changed in Unity's behaviour, too?

**Comment by zippopalermo** [comment]
Got it runnning successfully now. 

Solution was to delete the ProjectDirectory and have the application rebuild everything from scratch. No clue why it didn't work the first time. Up and running now anyway.

Thanks for the quick response.

**Comment by zippopalermo** [comment]
Solved

**Comment by toverux** [comment]
Glad to hear that! Never observed that myself before. If that should happen again, I'm afraid we wouldn't be able to offer direct support (although we still use this library in production), so feel free to investigate and propose a PR fixing it.
